### ISSUE TITLE
[RTL Support] RTL languages look weird when using default dialog

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [Stacked-Org/stacked#172] opened 2020-10-21 14:44 UTC
I suggest adding either a default check in the package or exposing something for the developer so he can flip the direction of the dialog, snackbar, etc..

**Comment by FilledStacks** [comment] 2020-10-22 05:43
Will look at this when I get some time and figure out what to expose.

**Comment by YazeedAlKhalaf** [comment] 2020-10-22 08:58
Okay great 🚀

**Comment by rockz1999** [comment] 2021-02-11 10:02
please let know of any progress on RTL support, rtl languages can't be properly implemented in snackbars

**Comment by FilledStacks** [comment] 2021-02-12 11:39
@rockz1999 there's no progress. We haven't looked at it since it was filed. You're welcome to check what's needed and make a PR. This is a very low priority at the moment.

**Comment by FilledStacks** [comment] 2021-04-02 15:42
Closing until I can get an example with steps to reproduce and what's required from us to fix it. Will re-open when provided

**Closed as completed by FilledStacks** 2021-04-02 15:42 UTC
Labels: reproduce issues, p3
