### ISSUE TITLE
upgrade build_runner and analyzer to newest version

### ISSUE THREAD

**Issue by volethanh** [Stacked-Org/stacked#460] opened 2021-07-16 11:53 UTC
Hi,

i'm using the stack_generator and when I run the command `pub run build_runner build --delete-conflicting-outputs` get error. I think because I'm using `analyzer: ^2.0.0` and `build_runner: 2.0.6`

Thanks

**Comment by hurbes** [comment] 2021-07-17 16:35
That's odd. Can you please post what error you're getting?

**Comment by volethanh** [comment] 2021-07-19 03:07
this is what i've got

<img width="908" alt="Screen Shot 2021-07-19 at 10 06 07 AM" src="https://user-images.githubusercontent.com/46510130/126096964-c404082f-6045-486d-88bd-e987a89e3b77.png">

**Comment by hurbes** [comment] 2021-07-19 11:20
@volethanh  This is happening because of an earlier release of the analyzer there was a bug with defaultValueCode which always returned null for formal parameters so to bypass the bug we locked the analyzer version to 1.5.0 for time being. The bug seems to be fixed in `analyzer 2.0.0`, We'll update the analyzer version now and make a release for it soon.

**Comment by volethanh** [comment] 2021-07-26 02:14
thanks @hurbes

**Comment by FilledStacks** [comment] 2021-07-26 14:13
@hurbes has the analyzer been updated?

**Comment by hurbes** [comment] 2021-07-26 14:17
@FilledStacks yeah, I'll do the pr in a moment.

**Comment by davidferraro** [comment] 2021-08-05 16:06
Not sure if this is related, but I am getting the following error as well when running `flutter pub run build_runner build --delete-conflicting-outputs`

> [SEVERE] stacked_generator:stackedRouterGenerator on lib/app/app.dart (cached):
> FormatException: Not an instance of Type.

This is a new project with the following dev dependencies:
```
dev_dependencies:
  build_runner:
  stacked_generator: ^0.5.2
  analyzer: ^2.0.0
```

My app.dart file looks like this:
```
import 'package:...../ui/views/startup/startup_view.dart';
import 'package:stacked/stacked_annotations.dart';

@StackedApp(routes: [
  MaterialRoute(page: StartupView, initial: true, name: "startupViewRoute"),
])
class AppSetup { }
```

**Comment by FilledStacks** [comment] 2021-08-06 07:12
Are you on the latest of everything when you run `flutter pub outdated`? @davidferraro

**Comment by davidferraro** [comment] 2021-08-06 13:11
Everything is latest except flutter_hooks which is at 0.17.0 because stacked_hooks 0.2.1 depends on it.

**Comment by FilledStacks** [comment] 2021-08-17 08:34
Got it. I have no idea why that's happening. If you can provide a small reproducible example that would help us in solving this

**Comment by davidferraro** [comment] 2021-08-18 21:17
Not positive what changed but the issue resolved itself. My only guess is there was some issue in the view class. Thanks for everything.

**Closed as completed** 2021-09-07 16:09 UTC
