### ISSUE TITLE
stacked_themes update provider to latest 6.0.1

### ISSUE THREAD

**Issue by azazadev** [Stacked-Org/stacked#511] opened 2021-10-06 13:45 UTC
- it is possible to upgrade provider to 6.0.1
and please also remove or integrate the package flutter_statusbarcolor_ns ( https://github.com/FilledStacks/stacked/issues/501 )

**Comment by azazadev** [comment] 2021-11-17 13:22
any update please ?

**Comment by FilledStacks** [comment] 2021-12-09 14:35
@azazadev the package we're using is not being updated. When they update we'll bump our version too.

**Comment by FilledStacks** [comment] 2022-01-19 03:33
Duplicate of #501

**Closed as completed by FilledStacks** 2022-01-19 03:33 UTC
Labels: p3
