### ISSUE TITLE
Add color parameter to showDialog in StackedServices

### ISSUE THREAD

**Issue by colbymaloy** [Stacked-Org/stacked#178] opened 2020-11-08 16:17 UTC
it would be nice to have a color parameter to avoid blinding white dialogs and avoid having to make a custom dialog to get around it. no complaints other than that! thanks for your hard work

**Comment by FilledStacks** [comment] 2020-11-09 04:42
Sup @AvatarDevs ! Long time 😄 There is a ticket for this already #147 it will be worked on at some point, don't know when. We're quite busy at the moment with some releases. But it'll be implemented soon to use the brightness property and show a less blinding color for darkmodes.

**Comment by FilledStacks** [comment] 2020-11-09 04:42
Duplicate of #147

**Closed as completed by FilledStacks** 2020-11-09 04:42 UTC
