### ISSUE TITLE
[bug]: Upgrading stacked_generator from 0.5.7 to 1.3.3

### ISSUE THREAD

**Issue by PieroScalapay** [Stacked-Org/stacked#959] opened 2023-05-23 15:27 UTC
### Describe the bug

Hello, and sorry in advance for long bug reporting, but I'm relatively new with Stacked (I appreciate it really a lot tought) and build_runner.

Scenario: my company needs to upgrade flutter to 3.10 and many old libraries, which, as you can imagine is usually a big PITA if the updates are not made often.

The old version of stacked was 2.3.15, and upgrading to 3.2.7 was relatively easy.
The problem arised upgrading stacked_generator, which is used by build_runner for generating routes.
Note: in the dev_dependendencies i see thta auto_router_generator is used (5.0.3). I tried to comment it for fixing the problem but didn't help.

The problem is that the generator now builds a very different type of router.dart, which contains errors. The description below explain in details.

### To reproduce

With stacked_generator 0.5.7 and stacked 2.2.8 I had this (extract of) `router.dart` file:
```
@StackedApp(routes: [
  MaterialRoute(
    path: '/shop',
    page: ShopNavigationStackScreen,
    children: [
      MaterialRoute(
        path: '/shop/giftguide',
        page: GiftGuideScreen,
      ),
    ],
  ),
  MaterialRoute(
      path: '/explore',
      page: ExploreNavigationStackScreen,
      children: [
        MaterialRoute(
          path: '/explore/giftguide',
          page: GiftGuideScreen,
        ),
      ])
])
```

This generated `router.router.dart` file is this:

```
class Routes {
  static const String shopNavigationStackScreen = '/shop';
  static const String exploreNavigationStackScreen = '/explore';
  static const all = <String>{
    shopNavigationStackScreen,
    exploreNavigationStackScreen,
  };
}

class StackedRouter extends RouterBase {
  @override
  List<RouteDef> get routes => _routes;
  final _routes = <RouteDef>[
    RouteDef(
      Routes.shopNavigationStackScreen,
      page: ShopNavigationStackScreen,
      generator: ShopNavigationStackScreenRouter(),
    ),
    RouteDef(
      Routes.exploreNavigationStackScreen,
      page: ExploreNavigationStackScreen,
      generator: ExploreNavigationStackScreenRouter(),
    ),
  ];
  @override
  Map<Type, StackedRouteFactory> get pagesMap => _pagesMap;
  final _pagesMap = <Type, StackedRouteFactory>{
    ShopNavigationStackScreen: (data) {
      return MaterialPageRoute<dynamic>(
        builder: (context) => const ShopNavigationStackScreen(),
        settings: data,
      );
    },
    ExploreNavigationStackScreen: (data) {
      return MaterialPageRoute<dynamic>(
        builder: (context) => const ExploreNavigationStackScreen(),
        settings: data,
      );
    },
  };
}

class ShopNavigationStackScreenRoutes {
  static const String giftGuideScreen = '/shop/giftguide';
  static const all = <String>{
    giftGuideScreen,
  };
}

class ShopNavigationStackScreenRouter extends RouterBase {
  @override
  List<RouteDef> get routes => _routes;
  final _routes = <RouteDef>[
    RouteDef(ShopNavigationStackScreenRoutes.giftGuideScreen,
        page: GiftGuideScreen),
  ];
  @override
  Map<Type, StackedRouteFactory> get pagesMap => _pagesMap;
  final _pagesMap = <Type, StackedRouteFactory>{
    GiftGuideScreen: (data) {
      var args = data.getArgs<GiftGuideScreenArguments>(nullOk: false);
      return MaterialPageRoute<dynamic>(
        builder: (context) => GiftGuideScreen(
          key: args.key,
          groupId: args.groupId,
        ),
        settings: data,
      );
    },
  };
}

class ExploreNavigationStackScreenRoutes {
  static const String giftGuideScreen = '/explore/giftguide';
  static const all = <String>{
    giftGuideScreen,
  };
}

class ExploreNavigationStackScreenRouter extends RouterBase {
  @override
  List<RouteDef> get routes => _routes;
  final _routes = <RouteDef>[
    RouteDef(ExploreNavigationStackScreenRoutes.giftGuideScreen,
        page: GiftGuideScreen),
  ];
  @override
  Map<Type, StackedRouteFactory> get pagesMap => _pagesMap;
  final _pagesMap = <Type, StackedRouteFactory>{
    GiftGuideScreen: (data) {
      var args = data.getArgs<GiftGuideScreenArguments>(nullOk: false);
      return MaterialPageRoute<dynamic>(
        builder: (context) => GiftGuideScreen(
          key: args.key,
          groupId: args.groupId,
        ),
        settings: data,
      );
    },
  };
}

/// ************************************************************************
/// Arguments holder classes
/// *************************************************************************

/// GiftGuideScreen arguments holder class
class GiftGuideScreenArguments {
  final Key? key;
  final String groupId;
  GiftGuideScreenArguments({this.key, required this.groupId});
}
```

Please note: the `GiftGuideScreenArguments` is generated once and used by both the parent routes.

Upgrading to stacked 3.2.7 and stacked_generator to 1.3.3 the build_runner gives an error:
```
[SEVERE] stacked_generator:stackedRouterGenerator on lib/router.dart:

InvalidGeneratorInputException: message: Child [/shop/giftguide] can not start with a forward slash
 todo: 
 element: null
package:stacked_generator/utils.dart 35:3                                                       throwError
package:stacked_generator/utils.dart 30:5                                                       throwIf
package:stacked_generator/src/generators/router_2/resolvers/route_config_resolver.dart 92:5     RouteConfigResolver.resolve
package:stacked_generator/src/generators/router_2/resolvers/router_config_resolver.dart 126:29  RouterConfigResolver._resolveRoutes
package:stacked_generator/src/generators/router_2/resolvers/router_config_resolver.dart 140:28  RouterConfigResolver._resolveRoutes
package:stacked_generator/src/generators/router_2/resolvers/router_config_resolver.dart 105:18  RouterConfigResolver.resolve
package:stacked_generator/src/generators/router/stacked_router_generator.dart 23:10             StackedNavigatorGenerator.generateForAnnotatedElement
```

Just for test I removed the path parameter from both the parent routes, and the `router.router.dart` is generated, but with an error. The error is that a class `NestedGiftGuideScreenArguments` (which I think corresponds to the old `GiftGuideScreenArguments`) is generated twice.

This is the new `router.router.dart` file generated:

```
 class Routes {
  static const shopNavigationStackScreen = '/shop';

  static const exploreNavigationStackScreen = '/explore';

  static const all = <String>{
    shopNavigationStackScreen,
    exploreNavigationStackScreen,
  };
}

class StackedRouter extends _i1.RouterBase {
  final _routes = <_i1.RouteDef>[
    _i1.RouteDef(
      Routes.shopNavigationStackScreen,
      page: _i2.ShopNavigationStackScreen,
    ),
    _i1.RouteDef(
      Routes.exploreNavigationStackScreen,
      page: _i3.ExploreNavigationStackScreen,
    ),
  ];

  final _pagesMap = <Type, _i1.StackedRouteFactory>{
    _i2.ShopNavigationStackScreen: (data) {
      return _i4.MaterialPageRoute<dynamic>(
        builder: (context) => const _i2.ShopNavigationStackScreen(),
        settings: data,
      );
    },
    _i3.ExploreNavigationStackScreen: (data) {
      return _i4.MaterialPageRoute<dynamic>(
        builder: (context) => const _i3.ExploreNavigationStackScreen(),
        settings: data,
      );
    },
  };

  @override
  List<_i1.RouteDef> get routes => _routes;
  @override
  Map<Type, _i1.StackedRouteFactory> get pagesMap => _pagesMap;
}

class ShopNavigationStackScreenRoutes {
  static const giftGuideScreen = 'gift-guide-screen';

  static const all = <String>{giftGuideScreen};
}

class ShopNavigationStackScreenRouter extends _i1.RouterBase {
  final _routes = <_i1.RouteDef>[
    _i1.RouteDef(
      ShopNavigationStackScreenRoutes.giftGuideScreen,
      page: _i5.GiftGuideScreen,
    )
  ];

  final _pagesMap = <Type, _i1.StackedRouteFactory>{
    _i5.GiftGuideScreen: (data) {
      final args = data.getArgs<NestedGiftGuideScreenArguments>(nullOk: false);
      return _i4.MaterialPageRoute<dynamic>(
        builder: (context) =>
            _i5.GiftGuideScreen(key: args.key, groupId: args.groupId),
        settings: data,
      );
    }
  };

  @override
  List<_i1.RouteDef> get routes => _routes;
  @override
  Map<Type, _i1.StackedRouteFactory> get pagesMap => _pagesMap;
}

class NestedGiftGuideScreenArguments {
  const NestedGiftGuideScreenArguments({
    this.key,
    required this.groupId,
  });

  final _i4.Key? key;

  final String groupId;

  @override
  String toString() {
    return '{"key": "$key", "groupId": "$groupId"}';
  }

  @override
  bool operator ==(covariant NestedGiftGuideScreenArguments other) {
    if (identical(this, other)) return true;
    return other.key == key && other.groupId == groupId;
  }

  @override
  int get hashCode {
    return key.hashCode ^ groupId.hashCode;
  }
}

class ExploreNavigationStackScreenRoutes {
  static const giftGuideScreen = 'gift-guide-screen';

  static const all = <String>{giftGuideScreen};
}

class ExploreNavigationStackScreenRouter extends _i1.RouterBase {
  final _routes = <_i1.RouteDef>[
    _i1.RouteDef(
      ExploreNavigationStackScreenRoutes.giftGuideScreen,
      page: _i5.GiftGuideScreen,
    )
  ];

  final _pagesMap = <Type, _i1.StackedRouteFactory>{
    _i5.GiftGuideScreen: (data) {
      final args = data.getArgs<NestedGiftGuideScreenArguments>(nullOk: false);
      return _i4.MaterialPageRoute<dynamic>(
        builder: (context) =>
            _i5.GiftGuideScreen(key: args.key, groupId: args.groupId),
        settings: data,
      );
    }
  };

  @override
  List<_i1.RouteDef> get routes => _routes;
  @override
  Map<Type, _i1.StackedRouteFactory> get pagesMap => _pagesMap;
}

class NestedGiftGuideScreenArguments {
  const NestedGiftGuideScreenArguments({
    this.key,
    required this.groupId,
  });

  final _i4.Key? key;

  final String groupId;

  @override
  String toString() {
    return '{"key": "$key", "groupId": "$groupId"}';
  }

  @override
  bool operator ==(covariant NestedGiftGuideScreenArguments other) {
    if (identical(this, other)) return true;
    return other.key == key && other.groupId == groupId;
  }

  @override
  int get hashCode {
    return key.hashCode ^ groupId.hashCode;
  }
}

extension NavigatorStateExtension on _i6.NavigationService {
  Future<dynamic> navigateToShopNavigationStackScreen([
    int? routerId,
    bool preventDuplicates = true,
    Map<String, String>? parameters,
    Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)?
        transition,
  ]) async {
    return navigateTo<dynamic>(Routes.shopNavigationStackScreen,
        id: routerId,
        preventDuplicates: preventDuplicates,
        parameters: parameters,
        transition: transition);
  }

  Future<dynamic> navigateToExploreNavigationStackScreen([
    int? routerId,
    bool preventDuplicates = true,
    Map<String, String>? parameters,
    Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)?
        transition,
  ]) async {
    return navigateTo<dynamic>(Routes.exploreNavigationStackScreen,
        id: routerId,
        preventDuplicates: preventDuplicates,
        parameters: parameters,
        transition: transition);
  }

  Future<dynamic>
      navigateToNestedGiftGuideScreenInShopNavigationStackScreenRouter({
    _i4.Key? key,
    required String groupId,
    int? routerId,
    bool preventDuplicates = true,
    Map<String, String>? parameters,
    Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)?
        transition,
  }) async {
    return navigateTo<dynamic>(ShopNavigationStackScreenRoutes.giftGuideScreen,
        arguments: NestedGiftGuideScreenArguments(key: key, groupId: groupId),
        id: routerId,
        preventDuplicates: preventDuplicates,
        parameters: parameters,
        transition: transition);
  }

  Future<dynamic>
      navigateToNestedGiftGuideScreenInExploreNavigationStackScreenRouter({
    _i4.Key? key,
    required String groupId,
    int? routerId,
    bool preventDuplicates = true,
    Map<String, String>? parameters,
    Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)?
        transition,
  }) async {
    return navigateTo<dynamic>(
        ExploreNavigationStackScreenRoutes.giftGuideScreen,
        arguments: NestedGiftGuideScreenArguments(key: key, groupId: groupId),
        id: routerId,
        preventDuplicates: preventDuplicates,
        parameters: parameters,
        transition: transition);
  }

  Future<dynamic> replaceWithShopNavigationStackScreen([
    int? routerId,
    bool preventDuplicates = true,
    Map<String, String>? parameters,
    Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)?
        transition,
  ]) async {
    return replaceWith<dynamic>(Routes.shopNavigationStackScreen,
        id: routerId,
        preventDuplicates: preventDuplicates,
        parameters: parameters,
        transition: transition);
  }

  Future<dynamic> replaceWithExploreNavigationStackScreen([
    int? routerId,
    bool preventDuplicates = true,
    Map<String, String>? parameters,
    Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)?
        transition,
  ]) async {
    return replaceWith<dynamic>(Routes.exploreNavigationStackScreen,
        id: routerId,
        preventDuplicates: preventDuplicates,
        parameters: parameters,
        transition: transition);
  }

  Future<dynamic>
      replaceWithNestedGiftGuideScreenInShopNavigationStackScreenRouter({
    _i4.Key? key,
    required String groupId,
    int? routerId,
    bool preventDuplicates = true,
    Map<String, String>? parameters,
    Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)?
        transition,
  }) async {
    return replaceWith<dynamic>(ShopNavigationStackScreenRoutes.giftGuideScreen,
        arguments: NestedGiftGuideScreenArguments(key: key, groupId: groupId),
        id: routerId,
        preventDuplicates: preventDuplicates,
        parameters: parameters,
        transition: transition);
  }

  Future<dynamic>
      replaceWithNestedGiftGuideScreenInExploreNavigationStackScreenRouter({
    _i4.Key? key,
    required String groupId,
    int? routerId,
    bool preventDuplicates = true,
    Map<String, String>? parameters,
    Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)?
        transition,
  }) async {
    return replaceWith<dynamic>(
        ExploreNavigationStackScreenRoutes.giftGuideScreen,
        arguments: NestedGiftGuideScreenArguments(key: key, groupId: groupId),
        id: routerId,
        preventDuplicates: preventDuplicates,
        parameters: parameters,
        transition: transition);
  }
}
```

I think my fix creates more problem than it solves.
I'm surely missing something but I cannot find any doc with my scenario.
My goal is being able to generate again my router.router.dart. I don't care if I need to change the code for matching the new type of routing (if changed).
Any help would be really appreciated.

**Comment by FilledStacks** [comment] 2023-05-26 15:19
Wow, that's a pretty old version to jump from. There's been so many changes since then. 

If you can reproduce this in a small example then we'd be able to help. unfortunately it's very difficult to debug something, as you can imagine without code. 

It's difficult when you have the code with you, imagine doing it without the code 😅

We'll take a look at this on Monday and get back to you.

**Comment by PieroScalapay** [comment] 2023-05-26 15:21
Yeah it is, but I'm 90% sure it is related to some api change in auto_route, because the code generated is completely different.

**Comment by FilledStacks** [comment] 2023-05-31 13:34
Yeah, we forked the latest version of auto_route and merged that into Stacked as well. That's for the navigator v2 version of the navigation service.

**Comment by PieroScalapay** [comment] 2023-05-31 13:39
Indeed, but the code of the generated code is completely different from old/new library. Strange there is no migration guide for that. I mean, I hope I was not the only one who started using stacked_generator from 0.5.x and upgrade to the next version. I hope to make an example, but that will not be so different than the example I posted above. Anyway thanks for the response

**Closed as completed** 2024-10-04 10:20 UTC
