### ISSUE TITLE
Error when loading screen

### ISSUE THREAD

**Issue by brianschardt** [Stacked-Org/stacked#21] opened 2020-05-03 17:49 UTC
Followed documentation not sure what could be causing this.
```
setState() or markNeedsBuild() called during build.


This _DefaultInheritedProviderScope<ProfileViewModel> widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
```

**Comment by FilledStacks** [comment] 2020-05-04 03:20
@brianschardt could be some of the changes i made. Can you give me the widget / viewmodel that's causing it on your side.

**Comment by YazeedAlKhalaf** [comment] 2020-05-08 02:15
It happened to me once, I think because you called `notifyListeners() ;` from within the build method not within the viewModel. Since `notifyListeners() ;` calls the build method, it will make an exception if you call it from inside.

Not sure though 😅

**Comment by FilledStacks** [comment] 2020-05-08 03:57
@YazeedAlKhalaf yes. That's usually when it happens. When trying to navigate while it's building or show a dialog as well. That will cause the error to show up.

**Comment by YazeedAlKhalaf** [comment] 2020-05-11 19:45
@brianschardt 
Was the issue solved?

**Comment by muhmmedAbdelkhalik** [comment] 2020-05-19 09:52
![2020-05-19 at 11 51 AM](https://user-images.githubusercontent.com/55117049/82312311-29613700-99c7-11ea-9c10-c1add53366a6.png)
i' have same issue @FilledStacks will it be solve or there is way to solving it ?

**Comment by FilledStacks** [comment] 2020-05-19 13:13
@muhmmedAbdelkhalik this is a built in flutter widget. You can't call notifyListeners while it's busy building the UI. When is this happening for you?

**Comment by muhmmedAbdelkhalik** [comment] 2020-05-19 13:20
@FilledStacks 
i have using DefaultTabController widget which contain 3 TabBar with 3 TabBarView,
and in each tabbar it contain ViewModelBuilder<ViewModel>.reactive and try without using disposeViewModel it get for me error , then i use disposeViewModel: true , but it get to me error setState() or markNeedsBuild() called during build.

**Comment by muhmmedAbdelkhalik** [comment] 2020-05-20 08:38
@FilledStacks  ??

**Comment by FilledStacks** [comment] 2020-05-20 10:32
You're trying to rebuild the widget while it's rebuilding. Does it happen when you navigate to every tab or to a specific one? Paste the code for the function you're calling in onModelReady here if you have any calls. You can't rebuild a widget while it's building which means you're calling notifyListeners or trying to show a dialog, or trying to navigate or opening the keyboard, or doing anything that will cause a rebuild while that same view is being built.

**Comment by muhmmedAbdelkhalik** [comment] 2020-05-20 13:12
```
**--------------- List of Products ---------------**
class ListProducts extends StatelessWidget {
  int categoriesId;
  String categoriesName;
  ListProducts(this.categoriesName, this.categoriesId);
  bool checkGrid = false;

  void _settingModalBottomSheet(context) {
    showModalBottomSheet(
        context: context,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.only(topLeft: Radius.circular(10), topRight: Radius.circular(10))),
        builder: (BuildContext bc) {
          return SafeArea(
            child: Container(
              child: new Wrap(
                children: <Widget>[
                  Container(
                      child: Row(
                        children: <Widget>[
                          SvgPicture.asset(
                            'assets/icons/menu.svg',
                            fit: BoxFit.fill,
                            height: 19,
                            color: ThemeCustom.greyColor,
                          ),
                          SizedBox(
                            width: 10,
                          ),
                          Text(
                            translate('products.choose_sort'),
                            style: GoogleFonts.openSans(
                              color: ThemeCustom.greyColor,
                              fontSize: 14,
                            ),
                          ),
                        ],
                        mainAxisAlignment: MainAxisAlignment.center,
                        crossAxisAlignment: CrossAxisAlignment.center,
                      ),
                      alignment: Alignment.center,
                      width: double.infinity,
                      margin: EdgeInsets.only(top: 20, bottom: 10)),
                  new ListTile(
                    title: new Text(
                      translate('products.newest'),
                      style: GoogleFonts.openSans(
                        color: locator<ListProductsViewModel>().lastSort == 'z to a'
                            ? ThemeCustom.primaryColor
                            : ThemeCustom.greyColor,
                        fontSize: 14,
                      ),
                    ),
                    onTap: () => locator<ListProductsViewModel>().sorting(bc, this.categoriesId, 'z to a'),
                  ),
                  new ListTile(
                    title: new Text(
                      translate('products.oldest'),
                      style: GoogleFonts.openSans(
                        color: locator<ListProductsViewModel>().lastSort == 'a to z'
                            ? ThemeCustom.primaryColor
                            :ThemeCustom.greyColor,
                        fontSize: 14,
                      ),
                    ),
                    onTap: () => locator<ListProductsViewModel>().sorting(bc, this.categoriesId, 'a to z'),
                  ),
                  new ListTile(
                    title: new Text(
                      translate('products.h_t_l'),
                      style: GoogleFonts.openSans(
                        color: locator<ListProductsViewModel>().lastSort == 'high to low'
                            ? ThemeCustom.primaryColor
                            :ThemeCustom.greyColor,
                        fontSize: 14,
                      ),
                    ),
                    onTap: () => locator<ListProductsViewModel>().sorting(bc, this.categoriesId, 'high to low'),
                  ),
                  new ListTile(
                    title: new Text(
                      translate('products.l_t_h'),
                      style: GoogleFonts.openSans(
                        color: locator<ListProductsViewModel>().lastSort == 'low to high'
                            ? ThemeCustom.primaryColor
                            :ThemeCustom.greyColor,
                        fontSize: 14,
                      ),
                    ),
                    onTap: () => locator<ListProductsViewModel>().sorting(bc, this.categoriesId, 'low to high'),
                  ),
                ],
              ),
            ),
          );
        });
  }

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 3,
      initialIndex: 0,
      child: Scaffold(
        appBar: CustomAppBar(
          title: this.categoriesName,
          products: true,
          actions: <Widget>[
            IconButton(
              icon: SvgPicture.asset(
                'assets/icons/categories.svg',
                fit: BoxFit.fill,
                height: 19,
                color: ThemeCustom.primaryColor,
              ),
              padding: EdgeInsets.all(0),
              onPressed: locator<ListProductsViewModel>().changeGrid,
            ),
            IconButton(
                icon: SvgPicture.asset(
                  'assets/icons/menu.svg',
                  fit: BoxFit.fill,
                  height: 19,
                ),
                padding: EdgeInsets.all(0),
                onPressed: () => _settingModalBottomSheet(context)),
            IconButton(
              icon: SvgPicture.asset(
                'assets/icons/filter.svg',
                fit: BoxFit.fill,
                height: 19,
              ),
              padding: EdgeInsets.all(0),
              onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (BuildContext context) => Filter())),
            ),
          ],
          bottoms: TabBar(
            unselectedLabelColor: ThemeCustom.greyColor,
            unselectedLabelStyle: TextStyle(fontWeight: FontWeight.normal),
            tabs: [
              Tab(
                  child: Text(
                translate('products.all'),
              )),
              Tab(
                  child: Text(
                translate('products.sells'),
              )),
              Tab(
                  child: Text(
                translate('products.rental'),
              )),
            ],
          ),
        ).build(context),
        body: TabBarView(
          children: [
            // Product (All)
            TabList(this.categoriesId, 'all'),
            // Product (Sells)
            TabList(this.categoriesId, 'sell'),
            // Product (Rental)
            TabList(this.categoriesId, 'rental'),
          ],
        ),
      ),
    );
  }
}
------------------------------------------------------------

**------------------ Tab List (1,2,3) -----------------------**
class TabList extends StatelessWidget {
  int categoriesId;
  String type;

  TabList(
      this.categoriesId,
      this.type,
      );

  @override
  Widget build(BuildContext context) {
    final connection = Provider.of<ConnectivityStatus>(context);
    return ViewModelBuilder<ListProductsViewModel>.reactive(
      viewModelBuilder: () => locator<ListProductsViewModel>(),
      disposeViewModel: false,
      onModelReady: (model) => model.initScreen(context, this.type, categoriesId, sort: null),
      builder: (context, model, child) {
        if (connection == ConnectivityStatus.Offline)
          return NoInternetWidget(retryFunc: () => model.initScreen(context, this.type, categoriesId));
        if (model.isBusy) return LoadingList(retryFunc: () => model.initScreen(context, this.type, categoriesId));
        if (model.products.isEmpty) return Text('Empty');
        if (model.products == null)
          return RefreshDataWidget(retryFunc: () => model.initScreen(context, this.type, categoriesId));
        return ListView(
          children: <Widget>[
            Column(
              children: <Widget>[
                SizedBox(
                  height: 10,
                ),
                OutlineButton.icon(
                  icon: SvgPicture.asset(
                    'assets/icons/megaphone.svg',
                    fit: BoxFit.fill,
                    height: 19,
                  ),
                  highlightedBorderColor: ThemeCustom.secondaryColor,
                  borderSide: BorderSide(color: ThemeCustom.greyColor),
                  label:
                  Text(translate('products.alert_me').toUpperCase(), style: ThemeCustom().secondFontProductPrice),
                  onPressed: () {
                    // Perform some action
                  },
                ),
                GridView.builder(
                  primary: false,
                  padding: const EdgeInsets.only(top: 5),
                  gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                    mainAxisSpacing: 2,
                    crossAxisCount: model.checkGrid ? 1 : 2,
                    childAspectRatio: model.checkGrid ? 3 : 0.95,
                  ),
                  scrollDirection: Axis.vertical,
                  physics: ScrollPhysics(),
                  itemCount: model.products.length,
                  shrinkWrap: true,
                  itemBuilder: (context, index) {
                    return CardProductList(index, model.checkGrid);
                  },
                ),
              ],
            ),
          ],
        );
      },
    );
  }
}
------------------------------------------------------------

**---------------------- ListProductsViewModel ----------------------**
class ListProductsViewModel extends BaseViewModel {
  ListProductsViewModel();

  Api _api = locator<Api>();
  List<Datum> _products = List();
  bool _refreshLiked = false;

  bool get refreshLiked => _refreshLiked;

  List<Datum> get products => _products;
  String lastType;
  String lastSort;
  bool checkGrid = false;

  // get data from server
  initScreen(context, type, categoriesId, {sort}) async {
    print('✅ init ✅');
    if (type == '') type = lastType;
//    _products.clear();
    setBusy(true);
    final r = await _api.getAllProduct(context: context, type: type, catId: categoriesId, sort: sort);
    await Future.delayed(Duration(milliseconds: 250));
    _products = r.data;
    print('_products=> ${_products[0].productsPrice}');
    lastType = type;
    lastSort = sort;
    setBusy(false);
  }

  changeGrid() {
    checkGrid = !checkGrid;
    notifyListeners();
  }

  sorting(ctx, catId, sort) async {
    Navigator.pop(ctx);
    await Future.delayed(Duration(milliseconds: 250));
    initScreen(ctx, '', catId, sort: sort);
  }
}
------------------------------------------------------------



```

**Comment by FilledStacks** [comment] 2020-05-20 13:18
@muhmmedAbdelkhalik so when does it happen. You didn't answer any of the questions above.

**Comment by muhmmedAbdelkhalik** [comment] 2020-05-20 13:19
@FilledStacks it happen when i swipe between any tab

**Comment by FilledStacks** [comment] 2020-05-20 13:24
Could be your `connection` variable that's being rebuilt while the view is being built already. 

Could also be multiple calls to init that might get triggered while the view is being rebuilt. 

Comment out those lines and see if it happens. Then when you add it back put it on a post frame callback to ensure you're not asking the view to rebuild while it's building itself. You can do that as follows.

```dart
SchedulerBinding.instance
          .addPostFrameCallback((_) => model.initScreen())
``` 

You have to identify what's causing it and fix that.

**Comment by muhmmedAbdelkhalik** [comment] 2020-05-20 13:31
hmmm , i make that now but still error show 
the problem in my model class i call on func initScreen()
for getting data from server and set data in list product but the problem is in the **setBusy**
which cause this error and i need it to make my view busy show loading screen until the data get it from server

**Comment by muhmmedAbdelkhalik** [comment] 2020-05-20 14:00
https://gph.is/g/EqXx07x
that what happen with me @FilledStacks

**Comment by FilledStacks** [comment] 2020-05-21 03:42
So tou put all your init acreens in a postFrameCallback?

**Comment by muhmmedAbdelkhalik** [comment] 2020-05-21 07:13
no

**Comment by FilledStacks** [comment] 2020-05-21 07:18
Once you do that I'll suggest other things to try after

**Comment by muhmmedAbdelkhalik** [comment] 2020-05-21 07:27
![2020-05-21 at 9 26 AM](https://user-images.githubusercontent.com/55117049/82534289-3310a900-9b45-11ea-9ae7-71e1c42dc6b2.png)
it get error also i have get all methods from my view model and put it in view ui 
and put this func like you said
WidgetsBinding.instance.addPostFrameCallback(afterBuild(context, this.type, categoriesId, sort: null));

**Comment by FilledStacks** [comment] 2020-05-21 09:13
You didn't write the code like I said. you need to provide a function like in the code snippet above. It's clear that these are not stacked problems. It would happen if you were using pure flutter as well and called setState while the UI is building so I'll most likely stop replying soon and close this. i wanted to fix it if it was a stacked problem.

```dart
SchedulerBinding.instance
          .addPostFrameCallback((_) => model.initScreen())
```

Take note of

```dart
(_) => model.initScreen()
```

A function that calls your function.

**Comment by muhmmedAbdelkhalik** [comment] 2020-05-21 11:08
i think the problem from tab bar structure because in any app they use custom tabbar

**Comment by FilledStacks** [comment] 2020-05-21 13:11
I use it too. The problem is described in the error. When you call setState while it's building the current UI then it'll throw an error because we currently don't have functionality to stop the execution of a function while it's being executed.

**Comment by YazeedAlKhalaf** [comment] 2020-05-21 15:23
Yup that needs to be solved because any widget which has multiple children moving in the screen such as:
• PageView

**Comment by muhmmedAbdelkhalik** [comment] 2020-05-21 15:30
@FilledStacks  
I don’t call setstate i just made func called initscreen to get data from serve and set data in ui
Do you have sample example of tab bar with using stacked with calling from server api data

**Comment by FilledStacks** [comment] 2020-05-21 16:47
in initscreen you call setBusy which calls notifyListeners which marks the widget for rebuild which is the same thing as calling setState. Which is why you have the error saying you're calling setState or markRebuild . I've also had the error before it was when I was doing that. It's easily solved by putting the call that marks your widget for a rebuild on a post frame callback.

If you comment out every call to initScreen does the error go away?

**Comment by FilledStacks** [comment] 2020-05-21 16:58
@muhmmedAbdelkhalik if you can make a small example on this happening I can show you how to fix it. I'll add the post frame callback where it's required and it should sort it out. [I showed it on my infinite scroll video moths back.](https://youtu.be/rr7d3SuhLiU?t=542) I explain the solution to fix it. So you need to apply that and your error will be gone.

**Comment by FilledStacks** [comment] 2020-05-21 17:00
Also @muhmmedAbdelkhalik is your viewmodel registered as a Factory or a singleton. Using a singleton in this scenario would be bad because they'll all trigger the same UI listeners meaning they will rebuild each other while the other one is building.

**Comment by muhmmedAbdelkhalik** [comment] 2020-05-22 02:37
**Very Thx** @FilledStacks ,
The problem is solved by 
1- put in onModelReady (model) => SchedulerBinding.instance.addPostFrameCallback((_) => model.initScreen())
2- change locator from registerLazySingleton -> registerFactory

**Comment by FilledStacks** [comment] 2020-05-22 05:14
@muhmmedAbdelkhalik happy to have helped.

**Closed as completed by FilledStacks** 2020-05-22 05:14 UTC
