### ISSUE TITLE
Need to have one reactive widget (VM) inside another one

### ISSUE THREAD

**Issue by sergiocasero** [Stacked-Org/stacked#207] opened 2021-01-30 19:06 UTC
Hello guys, first of all, thanks for this incredible package and community!.

I have a problem regarding the "complete rebuild" topic. The thing is that I want to have one reactive ViewModel inside another reactive ViewModel, is that possible??

I've checked https://www.filledstacks.com/post/flutter-state-management-with-stacked/ but when I try to call `notifyListeners()` on the child, I get the complete view updated, and I want to avoid that.

Why do I need this behavior?? Because I want to reuse a ViewModel from the mobile to web app.

Thanks again!

**Comment by FilledStacks** [comment] 2021-01-31 06:50
Hey @sergiocasero 

ViewModels should in most cases not know about each other. Each viewmodels notifyListeners call will only rebuild the widget / view it's associated with. 

It follows the Flutter build cycle so a widget will rebuild if Flutter thinks its different. If you have ViewA and inside a SmartWidgetA that has its own viewmodel. Then if you call notifyListeners in viewModelA then ViewA will rebuild. depending on how you SmartWidgetA is setup it won't rebuild the ViewModel for it. 

If you call notifyListeners in SmartWidgetAViewModel then ViewA will not be rebuilt. Only SmartWidgetA

**Comment by FilledStacks** [comment] 2021-01-31 06:51
I don't know if that helps. Maybe if you have a clearer example with details of what's happening that would help.

**Comment by sergiocasero** [comment] 2021-01-31 12:33
I'll try to reproduce it in a sample project, the thing that i want to replace is quite simple, in the mobile I have the tipical master/detail views, but I want to move them into a single page on the web.

I don't know what I'm doing wrong, but when the `child` calls `notify` the parent also knows it (WTF!!).

The example is a simple chat, like this UI: 

The "parent VM": Listen for a stream with the chatlist, and passes to the left panel the list of chats

```
await for(final chats in repository.observeChats()) {
      this._chats.clear();
      this._chats.addAll(chats);
      notify();
}
```
The "left panel": This also listen for the unread messages per chat.

The problem is that when the number of messages changes for 1 chat,

```
await for(final messages in repository.observeMessages(chat)) {
     this._messages.length = messages.length;
     notify(); // This notify is also "detected by the parent widget, and I get an infinite loop"
}
```

Hope this is enough, if not, I can create a project or something

**Comment by FilledStacks** [comment] 2021-02-02 08:01
I would need to have a reproducible problem otherwise if I had to write the code for this and do it the right way it'll work and there will be nothing to fix. If you can provide an example for me to run that shows the problem that would be great.

**Comment by FilledStacks** [comment] 2021-04-02 15:42
Closing because we don't know what is required here to make any changes.

**Closed as completed by FilledStacks** 2021-04-02 15:42 UTC
Labels: Feedback Requested
