### ISSUE TITLE
[stacked_services] [Snackbar] Snackbar does not popup until UI changes

### ISSUE THREAD

**Issue by RawahaOsi** [Stacked-Org/stacked#335] opened 2021-04-16 07:45 UTC
Hi, a weird behaviour was observed while development today.

I was using a custom snackbar and it won't popup until something on the UI changes!

Here is my code:

```
void setupSnackbarUi() {
  final service = locator<SnackbarService>();

  // Registers a config to be used when calling showSnackbar
  service.registerSnackbarConfig(SnackbarConfig(
    backgroundColor: Colors.red,
    textColor: Colors.white,
  ));

  service.registerCustomSnackbarConfig(
      variant: SnackbarType.SUCCESS, config: SnackbarConfig(backgroundColor: Colors.green));
}
```

`final snackbarService = locator<SnackbarService>(); // I initialize this  in my viewmodel`

```
snackbarService.showCustomSnackBar(
          variant: SnackbarType.SUCCESS,
          message: 'Settings have been restored',
          duration: Duration(seconds: 5));
```

I call the `showCustomSnackBar()` in a function in my viewmodel. The snackbar does not show until something on the UI changes, so as a hack when I did `notifyListeners();` right after the `showCustomSnackBar()`, it worked.

In other parts of the app, it works fine.

**Comment by drekembe** [comment] 2021-04-27 11:52
I'm triggering a snackbar from a service, and I get the same problem. In my service, I'm using firebase realtime DB to detect when the user's internet connection drops or is re-established and show a snackbar. At first I thought it's because I'm triggering it from a service instead of a viewmodel, but now I'm thinking it might be related to this.

**Comment by FilledStacks** [comment] 2021-04-28 15:54
Will assign this internally now to see what we can do.

**Comment by MDSADABWASIM** [comment] 2021-05-03 07:35
I am also getting the same issue, in my case I'm using the simple snackbar, snackbar appears but doesn't close, I need to drag it down to remove.

**Comment by FilledStacks** [comment] 2021-05-05 10:53
@MDSADABWASIM what the duration you're setting for you snackbar?

**Comment by MDSADABWASIM** [comment] 2021-05-05 10:54
> @MDSADABWASIM what the duration you're setting for you snackbar?

Seems like issue is gone from my side, I was setting 3 seconds duration.

**Comment by FilledStacks** [comment] 2021-05-05 12:59
We can't reproduce this issue.

**Comment by RawahaOsi** [comment] 2021-05-17 04:41
> > @MDSADABWASIM what the duration you're setting for you snackbar?
> 
> Seems like issue is gone from my side, I was setting 3 seconds duration.

Would you mind sharing the steps you used to resolve the issue? Or it just didn't happen anymore?

**Comment by MDSADABWASIM** [comment] 2021-05-17 04:44
> > > @MDSADABWASIM what the duration you're setting for you snackbar?
> > 
> > Seems like issue is gone from my side, I was setting 3 seconds duration.
> 
> Would you mind sharing the steps you used to resolve the issue? Or it just didn't happen anymore?

Yeah it stop happening itself, I think it was some issue on my side.

**Comment by FilledStacks** [comment] 2021-05-31 03:38
Is this still happening?

**Closed as completed** 2021-07-01 05:00 UTC
