### ISSUE TITLE
[BUG]  Required named parameter 'vsync' must be provided.  AnimatedSize(）

### ISSUE THREAD

**Issue by ifredom** [Stacked-Org/stacked#537] opened 2021-11-26 07:03 UTC
```

D:\workspace\ddlq-flutter-app2>flutter run
Launching lib\main.dart on MI PAD 4 PLUS in debug mode...
/D:/Asoftware/flutter/.pub-cache/hosted/pub.flutter-io.cn/stacked-2.2.7+1/lib/src/state_management/skeleton_loader.dart:103:29: Error: Required named parameter 'vsync' must be provided.
              ? AnimatedSize(
                            ^
/D:/Asoftware/flutter/packages/flutter/lib/src/widgets/animated_size.dart:56:9: Context: Found this candidate, but the arguments don't match.
  const AnimatedSize({
        ^^^^^^^^^^^^
/D:/Asoftware/flutter/.pub-cache/hosted/pub.flutter-io.cn/stacked-2.2.7+1/lib/src/state_management/skeleton_loader.dart:98:26: Error: Required named parameter 'vsync' must be provided.
      child: AnimatedSize(
                         ^
/D:/Asoftware/flutter/packages/flutter/lib/src/widgets/animated_size.dart:56:9: Context: Found this candidate, but the arguments don't match.
  const AnimatedSize({
        ^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'D:\Asoftware\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\Asoftware\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        31.3s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by hurbes** [comment] 2021-11-30 12:26
Duplicate of #521 
Hey, I think you're using an older version on flutter cause the `vsync` field in the AnimatedSize widget is deprecated after flutterv2.2.0-10.1.pre and it's not a required field anymore so it shouldn't be a problem.

**Comment by ifredom** [comment] 2021-12-07 07:29
> Duplicate of #521 Hey, I think you're using an older version on flutter cause the `vsync` field in the AnimatedSize widget is deprecated after flutterv2.2.0-10.1.pre and it's not a required field anymore so it shouldn't be a problem.

Thanks for recovering in time. It was solved after the upgrade. Due to the use of many third-party packages, it can not be easily upgraded at the beginning

**Closed as completed** 2021-12-15 02:20 UTC
