### ISSUE TITLE
Initialize annotated service with logger

### ISSUE THREAD

**Issue by manafire** [Stacked-Org/stacked#380] opened 2021-05-20 12:51 UTC
How would log be passed into the `stacked_firebase_auth` `FirebaseAuthenticationService`  declared with annotations in `app.dart`?   `getLogger` isn’t available until _after_ it is generated...

```dart
dependencies: [
    Singleton(classType: FirebaseAuthenticationService), // how to pass log: getLogger(..) in?
  ],
  logger: StackedLogger(),
```

```dart
/// Wraps the firebase auth functionality into a service
class FirebaseAuthenticationService {
  /// An Instance of Logger that can be used to log out what's happening in the service
  final Logger? log;
```

I thought you could use `resolveUsing` but the initializing file would still require `app.logger.dart` which wouldn't be available from scratch.  

I mentioned this awhile ago in Slack but re-raising here as I've started to extract parts of my app into packages and hit this logging order of operations dependency snag.  I'm fine to manually create the logger but since `stacked_firebase_auth` accepts a `log` param other folks may encounter this interesting issue.

Any thoughts, recommendations?

**Comment by manafire** [comment] 2021-05-20 13:10
Maybe there's a way for it to use a special string in a similar fashion to `logHelperName` that would resolve successfully in the generated code, if that's not too awkward.  Not sure how else to get around it.  `app.locator.dart` would also need to be generated with a dependency upon `app.logger.dart`.

**Comment by FilledStacks** [comment] 2021-05-31 03:43
@manafire this would all be solved if we solve the service injection into other services. I haven't had the time to think about and implement this just yet. I'll see if any of the internal devs are willing to spend some time on it.

**Comment by FilledStacks** [comment] 2022-01-19 03:27
This is a duplicate of #334

**Closed as completed by FilledStacks** 2022-01-19 03:27 UTC
Labels: p2, new feature
